# Default hyperparams
# Follows hyperparams from Dopamine:
# https://github.com/google/dopamine/blob/master/dopamine/agents/rainbow/configs/c51.gin

game: ['alien',
  'beam_rider',
  'breakout',
  'centipede',
  'enduro',
  'hero',
  'kung_fu_master',
  'ms_pacman',
  'qbert',
  'space_invaders']
spectral: ["middle", null]
