# DQN Minatar

game: [MinAtar-seaquest]
replay_path: [./results/2021Mar07-202512_minatar_dqn_replays/0002_estimator.args_.spectral_None__game_MinAtar-seaquest]

estimator:
  args_:
    spectral: [null, "-2"]