# DQN hyperparams as in the Nature paper. Follows hyperparams from Dopamine:
# github.com/google/dopamine/blob/master/dopamine/agents/dqn/configs/dqn_nature.gin

game: [
  bank_heist,
  battle_zone,
  berzerk,
  bowling,
  boxing,
]

estimator:
  args_:
    spectral: [null, -2]
