# DQN Minatar

experiment: MinAtar-DQN
device: cpu
save: yes
save_every_replay: False

epoch_cnt: 50
train_step_cnt: 100000
valid_step_cnt: 125000
val_epsilon: 0.001  # validation epsilone greedy

game: MinAtar-breakout

agent:
  name: DQN
  args_:
    epsilon: [linear, 1.0, 0.01, 250000, 5000]
    gamma: 0.99
    loss_fn: MSELoss
    update_freq: 4
    target_update_freq: 4000

replay_:
  capacity: 100000
  batch_size: 32
  hist_len: 1
  device: cpu

estimator:
  name: MinAtarNet
  args_:
    layer_dims: [[24, 24],[128]]
    spectral: null
    initializer: "xavier_uniform"  # this field can be missing

optim:
  name: "Adam"
  div_by_rho: no
  args_:
    lr: 0.00025
    eps: 0.0003125
