# DQN Minatar size sweep

game: [MinAtar-breakout, MinAtar-asterix, MinAtar-seaquest, MinAtar-space_invaders]

agent:
  args_:
    grad_penalty:
      k: [1.0]
      beta: [0.0000001, 0.00001, 0.001, 0.01, 0.1, 1.0]
      mode: ["avg_norm"]

estimator:
  args_:
    layer_dims:
      - [[24], [128]]
      - [[24, 24, 24], [128]]
