game: [MinAtar-breakout, MinAtar-asterix, MinAtar-seaquest, MinAtar-space_invaders]

estimator:
  args_:
    layer_dims:
      - [[20], [96]]
      - [[24], [128]]
      - [[28], [196]]
      - [[32], [256]]
      - [[20, 20], [96]]
      - [[24, 24], [128]]
      - [[28, 28], [196]]
      - [[32, 32], [256]]
      - [[20, 20, 20], [96]]
      - [[24, 24, 24], [128]]
      - [[28, 28, 28], [196]]
      - [[32, 32, 32], [256]]
