title: BBandit
seed: null

total_tasks: 30_000
total_eps_per_task: 1
total_eval_tasks: 300


env:
  spec: interpolation
  args_:
    total_trials: 100

agent:
  args_:
    gamma: [choice, [0.5, 0.6, 0.7, 0.8, 0.9, 0.99]]
    n_steps: 100
    coeff_critic: [choice, [0.0, 0.5, 1.0]]
    # start, end, total_steps ratio
    coeff_H: [1.0, 0.05, 0.5]
    with_interaction_hist: no
  optim:
    name: Adam
    clip_grad_norm: [choice, [10, 50]]
    args_:
      lr: [logUniform, [0.00001, 0.01]]
      eps: [logUniform, [0.000001, 0.001]]
