N: [3,4,5,6,7,8,9,10,11,12,13,14,15,16]

priority: [td, variance, uniform]

estimator:
  ensemble: [0, 21]

er:
  alpha: [0.95]

liftoff:
  - vars: [priority, er.alpha]
    "->": [[uniform, delete]]
  - vars: [priority, estimator.ensemble]
    "->": [[variance, 21]]