experiment: deadpan
N: 16
lr: 0.25
convergence_threshold: 0.001
max_steps: 1e7
cuda: True

priority: "uniform"
noise_variance: 0

mask_prob: 0.5
loss_fn: MSELoss

er:
  capacity: -1
  batch_size: 1
  hist_len: 1
  async_memory: no

estimator:
  linear: yes
  ensemble: 0