# DQN Minatar size sweep

game: [MinAtar-breakout, MinAtar-asterix, MinAtar-seaquest, MinAtar-space_invaders]

estimator:
  args_:
    layer_dims:
      - [[8], [32]]
      - [[16], [64]]
      - [[24], [128]]
      - [[32], [256]]

    spectral: ["-2", "-3"]

