N: [5,6,7,8,9,10,11,12,13,14,15,16]

estimator: [single, ensemble]
priority: [td, variance, uniform]

er:
  alpha: [0.95]

bootstrapping:
  B: [0, 21]
  mask_prob: [0.5]

liftoff:
  - vars: [priority, er.alpha]
    "->": [[uniform, delete]]
  - vars: [estimator, bootstrapping.B]
    "<=>": [[single, 0], [ensemble, 21]]