experiment: cs_dlv3  # cityscapes_DeepLabV3

epochs: 30  # roughly 60k iterations with batch size 10

seed: 42
device: cuda
cudnn_benchmark: yes

log_freq: 20
verbose: no

model:
  github: pytorch/vision
  model: deeplabv3_resnet101
  pretrained: no

dataset:
  name: Cityscapes
  root: ./data/Cityscapes/
  augmentation:
    strong: yes
loader:
  batch_size: 5
  num_workers: 16
  shuffle: yes
  pin_memory: yes

optim:
  lr: 0.00025
  momentum: 0.9
  weight_decay: 0.0005
scheduler:
  step_size: 10
  power: 0.9
cyclic:
  lrs: [0.0007, 0.0001]
  breaks: 0.5  # break at half-time

