experiment: vk_dlv2_vgg16  # vKitti_DeepLabV2

step_no: 90000
val_freq: 5000

seed: 42
device: cuda
cudnn_benchmark: yes

log_freq: 20
verbose: no

model:
  github: null
  model: deeplabv2_vgg16
  pretrained: no

dataset:
  name: VKITTI
  root: ./data/vkitti
  styled: no
  augmentation:
    strong: yes
loader:
  batch_size: 20
  num_workers: 20
  shuffle: yes
  pin_memory: false

optim:
  name: SGD
  per_layer_lr: yes
  args:
    lr: 0.00025
    momentum: 0.9
    weight_decay: 0.0005
scheduler:
  step_size: 10
  power: 0.9
# cyclic:
#   lrs: [0.0007, 0.0001]
#   breaks: 0.5  # break at half-time
