experiment: vk_dlv3  # vKitti_DeepLabV3

step_no: 90000
grad_acc_steps: 1  # no of gradient accumulation steps
val_freq: 1000

seed: 42
device: cuda
cudnn_benchmark: yes

log_freq: 50
verbose: no

model:
  github: pytorch/vision
  model: deeplabv3_resnet101
  pretrained: no
  pretrained_backbone: yes

dataset:
  name: VKITTI
  root: ./data/vkitti
  num_classes: 14
  styled: null
  style_ratio: 0.5
  augmentation:
    strong: yes
loader:
  batch_size: 10
  num_workers: 10
  shuffle: yes
  pin_memory: yes

optim:
  name: SGD
  args:
    lr: 0.002
    momentum: 0.9
    weight_decay: 0.0005
scheduler:
  name: "CosineAnnealingWarmRestarts"
  args:
    T_0: 3786
    T_mult: 2
    eta_min: 0.00001