
N: 6
lr: 0.25
threshold: 0.001
bias: True
update_target_freq: 0
max_steps: 20000
loss_fn: MSELoss

er:
  capacity: -1
  batch_size: 1
  hist_len: 1
  async_memory: no

exploration:
  name: "linear"
  start: 1.0
  end: 0.01
  steps: -1
  warmup_steps: -1
