title: metaVrl
seed: null

total_tasks: 20_000
total_eps_per_task: 1
total_eval_tasks: 300


env:
  spec: null
  args_:
    total_trials: 100

agent:
  args_:
    gamma: [choice, [0.7, 0.8, 0.9, 0.99]]
    n_steps: 100
    coeff_critic: [choice, [0.0, 0.5, 1.0]]
    coeff_H: [1.0, 0.05, 0.5]
    with_interaction_hist: no
  optim:
    name: [choice, [Adam, RMSprop]]
    clip_grad_norm: [choice, [0, 10, 50]]
    args_:
      lr: [logUniform, [0.0001, 0.01]]
      eps: [logUniform, [0.0000001, 0.001]]
