experiment: a2c_lld
algo: a2c
env_name: LunarLander-v2
base_seed: 42

training_steps: 200000
gamma: 0.99
nsteps: 60
beta_entropy: 0.001
lr: 0.001
hidden_size: 64

val_frequency: 25000 # steps
val_episodes: 100

log:
  frequency: 100  # episodes
  detailed: False