# Default hyperparams
# Follows hyperparams from Dopamine:
# https://github.com/google/dopamine/blob/master/dopamine/agents/rainbow/configs/c51_icml.gin

experiment: C51-ICML
device: cuda

game: pong
stochasticity: "random_starts"
agent:
  name: C51
  args_:
    epsilon: [linear, 1.0, 0.01, 1000000, 50000]
    gamma: 0.99
    clip_grad_norm: no
  save: yes

epoch_cnt: 200
train_step_cnt: 250000

update_freq: 4
target_update_freq: 10000

valid_step_cnt: 125000
val_epsilon: 0.001  # validation epsilone greedy

replay_:
  capacity: 1000000
  batch_size: 32
  hist_len: 4
  warmup_steps: 50000
  device: cpu
estimator:
  name: AtariNet
  args_:
    hidden_size: 512
    support: [-10, 10, 51]
    hist_len: 4
    spectral: null  # Usage: "-2","-3","-2,-3"
    initializer: "xavier_uniform"  # this field can be missing
optim:
  name: "Adam"
  args_:
    lr: 0.00025
    eps: 0.0003125
