# DQN hyperparams as in the Nature paper. Follows hyperparams from Dopamine:
# github.com/google/dopamine/blob/master/dopamine/agents/dqn/configs/dqn_nature.gin

game: [alien, beam_rider, qbert]

estimator:
  args_:
    spectral: [null, -2]
