# DQN hyperparams following Rainbow. Follows hyperparams from Dopamine:
# github.com/google/dopamine/blob/master/dopamine/agents/dqn/configs/dqn.gin

game: Pong

experiment: DQN
device: cuda
save: yes
replay_save_freq: 8

epoch_cnt: 200
train_step_cnt: 50000
valid_step_cnt: 50000
val_epsilon: 0.001  # validation epsilon greedy

agent:
  name: DQN
  args_:
    epsilon: [linear, 1.0, 0.01, 250000, 20000]
    gamma: 0.99
    loss_fn: MSELoss
    update_freq: 4
    target_update_freq: 8000

replay_:
  capacity: 1000000
  batch_size: 32
  hist_len: 4
  device: cuda

estimator:
  name: AtariNet
  args_:
    hidden_size: 512
    hist_len: 4
    spectral: null  # Usage: -1 or -2 or combined -1,-2,-3.
    lipschitz_k: 5
    random_power_iteration: yes
    initializer: "xavier_uniform"  # this field can be missing

optim:
  name: "Adam"
  args_:
    lr: 0.0000625
    eps: 0.0001500
