spectral: [null, fc2, fc1+fc2, fc0+fc1+fc2]
game: [cartpole/0,
  cartpole/1,
  cartpole/10,
  cartpole/11,
  cartpole/12,
  cartpole/13,
  cartpole/14,
  cartpole/15,
  cartpole/16,
  cartpole/17,
  cartpole/18,
  cartpole/19,
  cartpole/2,
  cartpole/3,
  cartpole/4,
  cartpole/5,
  cartpole/6,
  cartpole/7,
  cartpole/8,
  cartpole/9,
  cartpole_noise/0,
  cartpole_noise/1,
  cartpole_noise/10,
  cartpole_noise/11,
  cartpole_noise/12,
  cartpole_noise/13,
  cartpole_noise/14,
  cartpole_noise/15,
  cartpole_noise/16,
  cartpole_noise/17,
  cartpole_noise/18,
  cartpole_noise/19,
  cartpole_noise/2,
  cartpole_noise/3,
  cartpole_noise/4,
  cartpole_noise/5,
  cartpole_noise/6,
  cartpole_noise/7,
  cartpole_noise/8,
  cartpole_noise/9,
  catch/0,
  catch/1,
  catch/10,
  catch/11,
  catch/12,
  catch/13,
  catch/14,
  catch/15,
  catch/16,
  catch/17,
  catch/18,
  catch/19,
  catch/2,
  catch/3,
  catch/4,
  catch/5,
  catch/6,
  catch/7,
  catch/8,
  catch/9,
  catch_noise/0,
  catch_noise/1,
  catch_noise/10,
  catch_noise/11,
  catch_noise/12,
  catch_noise/13,
  catch_noise/14,
  catch_noise/15,
  catch_noise/16,
  catch_noise/17,
  catch_noise/18,
  catch_noise/19,
  catch_noise/2,
  catch_noise/3,
  catch_noise/4,
  catch_noise/5,
  catch_noise/6,
  catch_noise/7,
  catch_noise/8,
  catch_noise/9,
  discounting_chain/0,
  discounting_chain/1,
  discounting_chain/10,
  discounting_chain/11,
  discounting_chain/12,
  discounting_chain/13,
  discounting_chain/14,
  discounting_chain/15,
  discounting_chain/16,
  discounting_chain/17,
  discounting_chain/18,
  discounting_chain/19,
  discounting_chain/2,
  discounting_chain/3,
  discounting_chain/4,
  discounting_chain/5,
  discounting_chain/6,
  discounting_chain/7,
  discounting_chain/8,
  discounting_chain/9,
  memory_len/0,
  memory_len/1,
  memory_len/10,
  memory_len/11,
  memory_len/12,
  memory_len/13,
  memory_len/14,
  memory_len/15,
  memory_len/16,
  memory_len/17,
  memory_len/18,
  memory_len/19,
  memory_len/2,
  memory_len/20,
  memory_len/21,
  memory_len/22,
  memory_len/3,
  memory_len/4,
  memory_len/5,
  memory_len/6,
  memory_len/7,
  memory_len/8,
  memory_len/9,
  memory_size/0,
  memory_size/1,
  memory_size/10,
  memory_size/11,
  memory_size/12,
  memory_size/13,
  memory_size/14,
  memory_size/15,
  memory_size/16,
  memory_size/2,
  memory_size/3,
  memory_size/4,
  memory_size/5,
  memory_size/6,
  memory_size/7,
  memory_size/8,
  memory_size/9,
  mountain_car_noise/0,
  mountain_car_noise/1,
  mountain_car_noise/10,
  mountain_car_noise/11,
  mountain_car_noise/12,
  mountain_car_noise/13,
  mountain_car_noise/14,
  mountain_car_noise/15,
  mountain_car_noise/16,
  mountain_car_noise/17,
  mountain_car_noise/18,
  mountain_car_noise/19,
  mountain_car_noise/2,
  mountain_car_noise/3,
  mountain_car_noise/4,
  mountain_car_noise/5,
  mountain_car_noise/6,
  mountain_car_noise/7,
  mountain_car_noise/8,
  mountain_car_noise/9,
  umbrella_distract/0,
  umbrella_distract/1,
  umbrella_distract/10,
  umbrella_distract/11,
  umbrella_distract/12,
  umbrella_distract/13,
  umbrella_distract/14,
  umbrella_distract/15,
  umbrella_distract/16,
  umbrella_distract/17,
  umbrella_distract/18,
  umbrella_distract/19,
  umbrella_distract/2,
  umbrella_distract/20,
  umbrella_distract/21,
  umbrella_distract/22,
  umbrella_distract/3,
  umbrella_distract/4,
  umbrella_distract/5,
  umbrella_distract/6,
  umbrella_distract/7,
  umbrella_distract/8,
  umbrella_distract/9,
  umbrella_length/0,
  umbrella_length/1,
  umbrella_length/10,
  umbrella_length/11,
  umbrella_length/12,
  umbrella_length/13,
  umbrella_length/14,
  umbrella_length/15,
  umbrella_length/16,
  umbrella_length/17,
  umbrella_length/18,
  umbrella_length/19,
  umbrella_length/2,
  umbrella_length/20,
  umbrella_length/21,
  umbrella_length/22,
  umbrella_length/3,
  umbrella_length/4,
  umbrella_length/5,
  umbrella_length/6,
  umbrella_length/7,
  umbrella_length/8,
  umbrella_length/9]
