# DQN hyperparams as in the Nature paper. Follows hyperparams from Dopamine:
# github.com/google/dopamine/blob/master/dopamine/agents/dqn/configs/dqn_nature.gin

game: [
  wizard_of_wor,
  boxing,
  battle_zone,
  name_this_game,
  robotank,
  tutankham,
  seaquest,
  qbert,
  gopher,
  alien,
  solaris,
  pong,
  asterix,
  krull,
  ms_pacman,
  venture,
  private_eye,
  frostbite,
  up_n_down,
  road_runner,
  montezuma_revenge,
  video_pinball,
  gravitar,
  space_invaders,
  phoenix,
  atlantis,
  chopper_command,
  demon_attack,
  fishing_derby,
  amidar,
  ice_hockey,
  hero,
  zaxxon,
  kung_fu_master,
  star_gunner,
  bowling,
  berzerk,
  enduro,
  yars_revenge,
  jamesbond,
  crazy_climber,
  freeway,
  kangaroo,
  pitfall,
  beam_rider,
  centipede,
  time_pilot,
  tennis,
  riverraid,
  asteroids,
  bank_heist,
  breakout,
  double_dunk,
  assault,
  skiing,
]

estimator:
  args_:
    spectral: [null, -2, -3, -4]
