# DQN hyperparams as in the Nature paper. Follows hyperparams from Dopamine:
# github.com/google/dopamine/blob/master/dopamine/agents/dqn/configs/dqn_nature.gin

model:
  args_:
    hidden:
      - [128, 128, 128, 128]
      - [256, 256, 256, 256]
    conv_scale: [1, 2, 3]
    spectral: [
      null, "-2", "-3", "-4", "-5", "-6", "-7", "-8",
      "-2,-3", "-2,-3,-4,-5",
      "-2,-3,-4,-5,-6,-7", "-4,-5,-6,-7",
      "-2,-3,-4,-5,-6", "-3,-4,-5,-6", "-4,-5,-6", "-5,-6",
      "-4,-5,-6,-7,-8", "-6,-7,-8",
      "-2,-3,-4,-5,-6,-7,-8"
    ]

optimizer_:
  lr: [0.01, 0.001]

scheduler_:
  step_size: [100, 150]
