batch_size: 128
augmentation: yes
epochs: 250

model:
  name: SVHNNet
  args_:
    hidden: [64, 512, 64, 512]
    spectral: "-2"
    deep_conv: no

optimizer_:
  name: Adam
  lr: 0.001

scheduler_:
  name: StepLR
  step_size: 150
  gamma: 0.1
