# DQN Minatar

experiment: A2C-Brax-Sweep
device: cuda
# save: yes
# save_every_replay: False

epochs: 40
train_step_cnt: 25000  # these are "batched" steps
valid_ep_cnt: 4096  # some multiple of batch size

game: ant

agent:
  name: A2C
  batch_size: 1024
  nsteps: 50
  gamma: 0.99
  entropy_coeff: 0.001

estimator:
  name: ActorCritic
  args_:
    layer_dims: [64, 64]
    spectral: null

optim:
  name: "Adam"
  args_:
    lr: 0.001
    eps: 0.00001
