# DQN Minatar

game: [MinAtar-space_invaders]
replay_path: [./results/2021Mar07-202512_minatar_dqn_replays/0003_estimator.args_.spectral_None__game_MinAtar-space_invaders]

estimator:
  args_:
    spectral: [null, "-2"]