# Default hyperparams
# Follows hyperparams from Dopamine:
# https://github.com/google/dopamine/blob/master/dopamine/agents/rainbow/configs/c51.gin

experiment: DEV-DEBUG
device: cuda

game: CartPole-v1
agent:
  name: DQN
  args_:
    epsilon: ["linear", 1.0, 0.1, 100000, 5000]
    gamma: 0.99
    is_double: no  # double dqn
  save: no

epoch_cnt: 100
train_step_cnt: 10000

update_freq: 4
target_update_freq: 2048

valid_step_cnt: 50000
val_epsilon: 0.001  # validation epsilone greedy

replay_:
  capacity: 100000
  batch_size: 32
  hist_len: 1
  device: cpu
estimator:
  name: MLP
  args_:
    layers: [128, 128]  # output dims of hidden layers
    spectral: null
optim:
  name: "Adam"
  args_:
    lr: 0.0001
