
game: [ant]

agent:
  nsteps: [512, 1024, 2048]


estimator:
  args_:
    spectral:
      - null
      - {"actor": "-2", "critic": "-2"}
      - {"actor": "-2,-1", "critic": "-2"}
      - {"actor": "-3,-2,-1", "critic": "-2"}