# Default hyperparams
# Follows hyperparams from Dopamine:
# https://github.com/google/dopamine/blob/master/dopamine/agents/rainbow/configs/c51.gin

experiment: DEV-DEBUG
device: cuda

game: pong
stochasticity: "random_starts"
agent:
  name: C51
  args_:
    epsilon: [1.0, 0.05, 50000, 1000]
    gamma: 0.99
    clip_grad_norm: no
    loss_fn: SmoothL1Loss 
  save: yes

epoch_cnt: 200
train_step_cnt: 5000

update_freq: 4
target_update_freq: 8000

valid_step_cnt: 5000
val_epsilon: 0.001  # validation epsilone greedy

replay_:
  capacity: 1000000
  batch_size: 32
  hist_len: 4
  warmup_steps: 20000
  device: cpu
estimator:
  name: AtariNet
  args_:
    hidden_size: 512
    support: [-10, 10, 51]
    hist_len: 4
    spectral: -1L,-2, -3, -4L
    leave_smaller: True
    lipschitz_k: 10
    flow_through_norm: "linear"
    initializer: "xavier_uniform"  # this field can be missing
optim:
  name: "Adam"
  args_:
    lr: 0.00025
    eps: 0.0003125