game: [MinAtar-asterix, MinAtar-breakout, MinAtar-seaquest, MinAtar-space_invaders]

demon:
  args_:
    sigma: [0.1, 0.3, 0.4, 0.5, 1.0]
    kernel: [3]

estimator:
  args_:
    spectral: [null, "-2"]