N: [5,6,7,8,9,10,11,12,13,14,15,16, 17, 18]

priority: [td, variance, uniform]
estimator:
  ensemble: [3, 7, 11]

er:
  alpha: [0.7, 1.2]

liftoff:
  - vars: [priority, er.alpha]
    "->": [[uniform, delete]]
